// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package router

import (
	"chat_app/config"
	"chat_app/internal/handlers"
	"chat_app/internal/repositories"
	"chat_app/internal/services"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeAuthHanlder(db *gorm.DB, conf *config.Config) *handlers.AuthHandler {
	authRepository := repositories.NewAuthRepository(db)
	authService := services.NewAuthService(authRepository, conf)
	authHandler := handlers.NewAuthHandler(authService)
	return authHandler
}

func InitializeChatHanlder(db *gorm.DB, conf *config.Config) *handlers.ChatHandler {
	chatRepo := repositories.NewChatRepo(db)
	chatService := services.NewChatService(chatRepo)
	chatHandler := handlers.NewChathandler(chatService , conf.JwtSecret)
	return chatHandler
}
